# Generated by Django 3.1.7 on 2022-02-05 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category_comment_post_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='created_at',
        ),
    ]
