# Generated by Django 3.1.7 on 2022-01-28 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='store_name',
            field=models.CharField(max_length=255, verbose_name='科目名'),
        ),
    ]
